#!/bin/bash
# retreive_all_regions
# AWSCLI list all regions
# David Cook, Nov 3/2020
#

# HISTORY
# VER   DATE            WHO     STATUS
# v0.1  2020/11/03      dbc     Initial delivery


# CONSTANTS/VARS
DEBUG=0                                          # 0=no / 1<=yes
VER=0.1                                          # Script version number
OUTFILE="region-list_"`date +"%Y-%m-%d"`".txt"   # OUTFILE contains calculated runtime date


#
# Include Common Functions
. ./common_functions


#
# PRIVATE FUNCTIONS
# Functions private to this application


#
# MAIN

# Log start of program
logger "${SCRIPTNAME} Starting"


# Check if I am already running
am-i-running


# Delete if present and re-create the output file
[ -f ${OUTFILE} ] && rm ${OUTFILE}
touch ${OUTFILE}
rc=$?
[ $rc -gt 0 ] && logger "`basename $0` cannot create ${OUTFILE}. Exiting..." && exit 8


# Fetch from AWS
aws.get-all-regions
touch ${OUTFILE}
rc=$?
if [ $rc -gt 0 ]; then
   echo "Error creating file ${OUTFILE}"
   logger "${SCRIPTNAME} Error creating ${OUTFILE}"
   exit 9
fi
 

# Loop through results
for ITEM in ${REGIONS}
do
   echo "REG:"${ITEM} >> ${OUTFILE}
done

logger "${SCRIPTNAME} normal completion"

#
# EOF
#
