#!/bin/bash
# retreive_region_list
# AWSCLI list all regions
# David Cook, Nov 3/2020
#

aws ec2 describe-regions --region us-east-1 --output text --query "Regions[*].[RegionName]" | sort -h


#
# EOF
#
