#!/bin/bash
# updt_machine_type
#
# Updates the AWS InstanceType list.
# Script parses your current AWS flat file from 
# retrieve_all_ec2 script and adds new/unseen values with a 
# timestamp to the machinetype table.
#
# TABLE: MachineTYpe
#  id serial PK
#  MachineType varchar(20)
#  UpdtDate timestamp
# 
# HISTORY
# VER   DATE            WHO     STATUS
# v0.1  2020/11/03      dbc     Initial delivery
# v0.2	2020/11/17	dbc	Refactor removing common features into
#				common_functions module
# v0.3	2020/12/02	dbc	Supress std error output

# CONSTANTS/VARS
DEBUG=1                                          # 0=no / 1<=yes
VER=0.3                                          # Script version number
OUTFILE="ec2-list-all_"`date +"%Y-%m-%d"`".txt"  # OUTFILE contains calculated
						 # runtime date
ReportDate=$(echo ${OUTFILE} | sed -e 's/^.*_//' -e 's/\.txt//')

#
# Include Common Functions
. ./common_functions


#
# PRIVATE FUNCTIONS
# Functions private to this application


#
# MAIN


# Log start of program
logger "${SCRIPTNAME} Starting"


# Check if I am already running
am-i-running


# Does the source file exist?
[ ! -f ${OUTFILE} ] && echo "${OUTFILE} not present. Exiting." && exit 9


# Get list if unique machine types
LIST=$(cat ${OUTFILE} | awk 'BEGIN {FS=":"}; {print $6}' | sort -u)


# Loop through array and add new items to the database
for ITEM in $LIST
do
  echo "---> "$ITEM
  psql -d ${DB} -c "INSERT into machinetype (MachineType,UpdtDate) SELECT '$ITEM', now() WHERE NOT EXISTS ( SELECT 1 from machinetype WHERe machinetype='$ITEM');" 2>/dev/null
done


logger "${SCRIPTNAME} Normal completion"

#
# EOF
#
