#!/bin/bash
# updt_machine_type
#
# Updates the AWS InstanceType list.
# Script parses your current AWS flat file from 
# retrieve_all_ec2 script and adds new/unseen values with a 
# timestamp to the machinetype table.
#
# TABLE: MachineTYpe
#  id serial PK
#  MachineType varchar(20)
#  UpdtDate timestamp
# 


DB="inventory"
CREATE_TABLE=0


#
# MAIN


# Log start of program
logger "${SCRIPTNAME} Starting"


#
# Check if I am already running
# Note 1: You must provide full path name to binaries to ensure this
#         works in cron environments.
# Note 2: Do not enclose if statement in brackets or it will
#         execute as a sub-shell and break process.
#if /usr/sbin/pidof -x "`basename $0`" -o $$ >/dev/null; then
# MacOS doesn't have pidof, use ps ax & grep
#if [ $(ps ax | grep -i `basename $0` | grep -v grep  | wc -l) -gt 2 ]; then
if [ $(/bin/ps ax | /usr/bin/grep -i `/usr/bin/basename $0` | /usr/bin/grep -v grep  | /usr/bin/wc -l) -gt 2 ]; then
    logger "`basename $0` already running. Exiting..."
    echo "Process already running"
    exit 8
fi

# Create the table
if [ ${CREATE_TABLE} -gt 0 ]; then
   psql -d ${DB} -c "CREATE TABLE machinetype(id SERIAL PRIMARY KEY, MachineType varchar(20) UNIQUE NOT NULL, UpdtDate timestamp)"
   psql -d ${DB} -c "SELECT count(*) from machinetype;"
fi


# Get list if unique machine types
LIST=$(cat ec2-list-all_2020-11-10.txt | awk 'BEGIN {FS=":"}; {print $6}' | sort -u)


# Loop through array and add new items to the database
for ITEM in $LIST
do
  echo "---> "$ITEM
  psql -d ${DB} -c "INSERT into machinetype (MachineType,UpdtDate) SELECT '$ITEM', now() WHERE NOT EXISTS ( SELECT 1 from machinetype WHERe machinetype='$ITEM');"
done


logger "${SCRIPTNAME} Normal completion"

#
# EOF
#
