#!/bin/bash
# updt_machine_type
#
# Updates the AWS InstanceType list.
# Script parses your current AWS flat file from 
# retrieve_all_ec2 script and adds new/unseen values with a 
# timestamp to the machinetype table.
#
# TABLE: MachineTYpe
#  id serial PK
#  MachineType varchar(20)
#  UpdtDate timestamp
# 


CREATE_TABLE=0

#
# Include Common Functions
. ./common_functions


#
# PRIVATE FUNCTIONS
# Functions private to this application


#
# MAIN


# Log start of program
logger "${SCRIPTNAME} Starting"


# Check if I am already running
am-i-running


# Create the table
if [ ${CREATE_TABLE} -gt 0 ]; then
   psql -d ${DB} -c "CREATE TABLE machinetype(id SERIAL PRIMARY KEY, MachineType varchar(20) UNIQUE NOT NULL, UpdtDate timestamp)"
   psql -d ${DB} -c "SELECT count(*) from machinetype;"
fi


# Get list if unique machine types
LIST=$(cat ec2-list-all_2020-11-10.txt | awk 'BEGIN {FS=":"}; {print $6}' | sort -u)


# Loop through array and add new items to the database
for ITEM in $LIST
do
  echo "---> "$ITEM
  psql -d ${DB} -c "INSERT into machinetype (MachineType,UpdtDate) SELECT '$ITEM', now() WHERE NOT EXISTS ( SELECT 1 from machinetype WHERe machinetype='$ITEM');"
done


logger "${SCRIPTNAME} Normal completion"

#
# EOF
#
