#!/bin/bash
# updt_vpcs
#
# Updates the AWS VPC list.
# Script parses your current AWS flat file from 
# retrieve_all_vpcs script and adds new/unseen values with a 
# timestamp to the vpc table.
#
# TABLE: VPC
#  id serial
#  VpcId varchar(64) UNIQUE NOT NULL PRIMARY KEY
#  VpcRegion varchar(20) 
#  VpcNet varchar(20)
#  UpdtDate timestamp
# 
# HISTORY
# VER   DATE            WHO     STATUS
# v0.1  2020/11/03      dbc     Initial delivery
# v0.2	2020/12/02	dbc	Supress std error

# CONSTANTS/VARS
DEBUG=1                                          # 0=no / 1<=yes
VER=0.3                                          # Script version number
OUTFILE="vpc-list-all_"`date +"%Y-%m-%d"`".txt"  # OUTFILE contains calculated
						 # runtime date
ReportDate=$(echo ${OUTFILE} | sed -e 's/^.*_//' -e 's/\.txt//')


#
# Include Common Functions
. ./common_functions


#
# PRIVATE FUNCTIONS
# Functions private to this application


#
# MAIN


# Log start of program
logger "${SCRIPTNAME} Starting"

# Check if I am already running
am-i-running


# Does the source file exist?
[ ! -f ${OUTFILE} ] && echo "${OUTFILE} not present. Exiting." && exit 9

# Get list if unique machine types
LIST=$(cat ${OUTFILE})


# Loop through array and add new items to the database
for ITEM in $LIST
do
  VPCREGION=$(echo ${ITEM} | awk 'BEGIN {FS=":"}{print $2}')
  VPCID=$(echo ${ITEM} | awk 'BEGIN {FS=":"}{print $3}')
  VPCNET=$(echo ${ITEM} | awk 'BEGIN {FS=":"}{print $4}')
  if [ $DEBUG -gt 0 ]; then
     echo "VPCID     ---> "$VPCID
     echo "VPCREGION ---> "$VPCREGION
     echo "VPCNET    ---> "$VPCNET
  fi

  # Perform insert
  psql -d ${DB} -c "INSERT into VPC (VpcId,VpcRegion,VpcNet,UpdtDate) SELECT '$VPCID', '$VPCREGION', '$VPCNET',now() WHERE NOT EXISTS ( SELECT 1 from VPC WHERE VpcId='$VPCID');" 2>/dev/null
done

logger "${SCRIPTNAME} Normal completion"

#
# EOF
#
